kubectl delete -f - << EOF
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: edge-service
spec:
  template:
    metadata:
      name: edge-service-v1
      annotations:
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
      - name: edge-service
        image: dev.local/edge-service:0.1
        imagePullPolicy: Never
        args: ["mqtt-handler-response", "80"]
EOF
